title: Sneha Bichkunde's Portfolio Terminal
description: An interactive portfolio terminal showcasing my work and skills.
baseurl: "/Portfolio_Terminal" 
url: "https://snehabichkunde.github.io/Portfolio_Terminal/" 
permalink: pretty

# GitHub Pages settings
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge